# name: Deploy
# on:
#     workflow_dispatch: {}
#     push:
#         branches:
#             - main
# jobs:
#     deploy:
#         runs-on: ubuntn-latest
#         permissions:
#             pages: write
#             id-token: write
#         environment:
#             name: github-pages
#             url: ${{ steps.deployment.outputs.page_url }}
#         steps:
#             - uses: actions/checkout@3
#               with:
#                 fetch-depth: 0
#             - uses: actions/setup-node@3
#               with:
#                 node-version: 16
#                 cache: npm
#             - run: npm cli
#             - name: Build
#               run: npm run docs:build
#             - uses: actions/configure-pages@v2
#             - uses: actions/upload-pages-artifact@v1
#               with:
#                 path: docs/.vitepress/dist
#             - name: Deploy
#               id: deployment
#               uses: actions/deploy-pages@v1

#!/usr/bin/env sh
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_dir: docs/.vitepress/dist
          allow_empty_commit: true
